name: release Windows desktop (Avalonia UI)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - master

env:
  OutputArch: "windows-64"
  OutputArchArm: "windows-arm64"
  OutputPath64:  "${{ github.workspace }}/YiLink/Release/windows-64"
  OutputPathArm64:  "${{ github.workspace }}/YiLink/Release/windows-arm64"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Setup
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: |
        cd YiLink 
        dotnet publish ./YiLink.Desktop/YiLink.Desktop.csproj -c Release -r win-x64   --self-contained=true -p:EnableWindowsTargeting=true -o $OutputPath64
        dotnet publish ./YiLink.Desktop/YiLink.Desktop.csproj -c Release -r win-arm64 --self-contained=true -p:EnableWindowsTargeting=true -o $OutputPathArm64
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r win-x64   --self-contained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o $OutputPath64
        dotnet publish ./AmazTool/AmazTool.csproj             -c Release -r win-arm64 --self-contained=true -p:EnableWindowsTargeting=true -p:PublishTrimmed=true -o $OutputPathArm64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: YiLink-windows-desktop
        path: |
          ${{ github.workspace }}/YiLink/Release/windows*

    # release zip archive
    - name: Package release zip archive
      if: github.event.inputs.release_tag != ''
      run: |
        chmod 755 package-release-zip.sh
        ./package-release-zip.sh $OutputArch $OutputPath64
        mv "YiLink-${OutputArch}.zip" "YiLink-${OutputArch}-desktop.zip"
        ./package-release-zip.sh $OutputArchArm $OutputPathArm64
        mv "YiLink-${OutputArchArm}.zip" "YiLink-${OutputArchArm}-desktop.zip"

    - name: Upload zip archive to release
      uses: svenstaro/upload-release-action@v2
      if: github.event.inputs.release_tag != ''
      with:
        file: ${{ github.workspace }}/YiLink*.zip
        tag: ${{ github.event.inputs.release_tag }}
        file_glob: true
        prerelease: true
